name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2-beta
        with:
          version: 10.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Build Application
        run: npx ember build --enviroment=ci

      - name: Run deploy script
        uses: nataliebasket/github-pages-deploy-action@v4.2.2
        # uses: nataliebasket/flexberry-ember/github-pages-deploy-action@v4.2.2
        # uses: github-pages-deploy-action@v4.2.2
        # run: sh ./scripts/deploy-to-gh-pages.sh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./build
          branch: gh-pages

